name: Build

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24.x

      - name: Build
        run: make
