name: build targets
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.base-image }}
    strategy:
      fail-fast: true
      matrix:
        target:
          - freebsd-amd64
          - linux-amd64
          - linux-arm64
          - linux-armhf
          - windows-amd64
        include:
          - target: freebsd-amd64
            arch: amd64
            base-image: ubuntu-latest
            os: freebsd
          - target: linux-amd64
            arch: amd64
            base-image: ubuntu-latest
            build-image: amd64/debian:stable
            os: linux
          - target: linux-arm64
            arch: arm64
            base-image: ubuntu-latest
            build-image: arm64v8/debian:stable
            os: linux
          - target: linux-armhf
            arch: arm
            armver: 7
            base-image: ubuntu-latest
            build-image: arm64v8/debian:stable
            os: linux
          - target: windows-amd64
            arch: amd64
            base-image: ubuntu-latest
            ext: ".exe"
            os: windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch}} GOARM=${{ matrix.armver }} make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qtv-go-${{ matrix.target }}${{ matrix.ext }}
          path: qtv-go${{ matrix.ext }}
